[tool.poetry]
name = "bedrock-k"
version = "0.1.0"
description = ""
authors = ["KiloJon <social@kjon.life>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
